@startuml

entity Player {
  *id : BIGINT <<PK>>
  --
  *name : text
  *birthday : date
}

entity Booking {
  *id : BIGINT <<PK>>
  --
  *court : INT
  *player_id : BIGINT <<FK>>
  *start_time : TIMESTAMP
  *end_time : TIMESTAMP
}

Player ||--o{ Booking

@enduml
